filename=short_seq.fastq

sed -i 's/ATACTCCTGAAAGATAAGTGG/primer_fw/g' $filename
sed -i 's/CAACGGTAGAGTACTCGGCTTTTA/primer_fw/g' $filename
sed -i 's/TTTT[TC]ATGAAATACAAGATGCTC/primer_fw/g' $filename
sed -i 's/ATTTGAACTGGTGACACGAG/primer_fw/g' $filename
sed -i 's/GAAGTAGTAGGATTGATTCTC/primer_fw/g' $filename
sed -i 's/CCCTACAACTCATGAATTAAG/primer_fw/g' $filename
sed -i 's/CGCAGTTCTTCTGAATTTCGAATAG/primer_fw/g' $filename
sed -i 's/AAAGGGAGTGTGTGCGAGTTG/primer_fw/g' $filename
sed -i 's/CCAAAATATT[GTC]GGAGGACTCT/primer_fw/g' $filename
sed -i 's/GCCGCTTCCGTTATTGCTGCTGG/primer_fw/g' $filename
sed -i 's/GTTTAGTGGTAAAAGTGTGATTCGTT/primer_fw/g' $filename
sed -i 's/CCGCATCGTTAGCTTGGAAGGC/primer_fw/g' $filename
sed -i 's/GAACCCGTGACCTCAAGGTTATG/primer_fw/g' $filename
sed -i 's/TGGCGTGGATATTGGCAGGA/primer_fw/g' $filename
sed -i 's/GGTTCAAGTCCCTCTATCCC/primer_fw/g' $filename
sed -i 's/CAACATATACCACTGTCAAG/primer_fw/g' $filename
sed -i 's/CTCGCACACACTCCCTTTCC/primer_fw/g' $filename
sed -i 's/GTTTCATTCGGCTCCTTTAT/primer_fw/g' $filename
sed -i 's/CATTTCACGAAGTATGTGTCCG/primer_fw/g' $filename
sed -i 's/CAAGGCGGTGCTCTTCAGAAGG/primer_fw/g' $filename
sed -i 's/GCTGAGTGAGGCAGTGTGTGGC/primer_fw/g' $filename
sed -i 's/GTCCAAATGTGAGCAGCATTATCC/primer_fw/g' $filename
sed -i 's/ATCAGTCTGAAGCAGGCCTCG/primer_fw/g' $filename
sed -i 's/CCCGAAGTGTCCAGAGC/primer_fw/g' $filename
sed -i 's/CCCACTCAAATAGTCTAC/primer_fw/g' $filename
sed -i 's/CTACCACTGAGTTAAAAGGG/primer_fw/g' $filename
sed -i 's/ACCAATTGAACTACAATCCC/primer_fw/g' $filename
sed -i 's/GTC[ACT][AC]A[TC]TA[TC]CC[AT]ATGGT[TC]CCTGG/primer_fw/g' $filename
sed -i 's/GC[AT]ATCTT[GC]AC[AC]CCCATGTG/primer_fw/g' $filename
sed -i 's/TTCGTCG[GAT]CGTAGTAAATAG/primer_fw/g' $filename
sed -i 's/GTGAATCCACCA[TC]GCGCGGG/primer_fw/g' $filename
sed -i 's/AATGGTCTCTTACGAAGT[AC]TCT/primer_fw/g' $filename
sed -i 's/CCGCTTAGTGAGACAGATAT/primer_fw/g' $filename
sed -i 's/GCATTACGATCTGCAGCTCA/primer_fw/g' $filename
sed -i 's/GAGCGTTCATTTATCACCC/primer_fw/g' $filename
sed -i 's/CCATATCTGCCTTTGCG/primer_fw/g' $filename
sed -i 's/TGGGTTGCTAACTCAACGG/primer_fw/g' $filename
sed -i 's/AACTAGTCGGATGGAGTAG/primer_fw/g' $filename
sed -i 's/GAAGAGTTTCCGGTCGATCC/primer_fw/g' $filename
sed -i 's/GAATGGAAGAGTTTCCGG/primer_fw/g' $filename
sed -i 's/CGGGTTCGATTCCCGCTACC/primer_fw/g' $filename
sed -i 's/ATTGCGTCCAATAGGATTTGAA/primer_fw/g' $filename
sed -i 's/GGTATAGGTTCAAATCCTATTGGAC/primer_fw/g' $filename
sed -i 's/CCCTTTTGAAAGAAGCTATTCAGG/primer_fw/g' $filename
sed -i 's/GCCCTTTTAACTCAGTGGTA/primer_fw/g' $filename
sed -i 's/TACCAAGGGCTATAGTCAT/primer_fw/g' $filename
sed -i 's/CCCAGTCTGAAACCAAGTGG/primer_fw/g' $filename
sed -i 's/GTTGCTTT[TC]TACCACATCGTTT/primer_fw/g' $filename
sed -i 's/CCACTTGGTTTCAGACTGGG/primer_fw/g' $filename
sed -i 's/ATCTCCTTCATCGTCCAC/primer_fw/g' $filename
sed -i 's/CCCCAACTAATACCTAATCTAC/primer_fw/g' $filename
sed -i 's/TCGGCGCTTGATAGAGCCTAGG/primer_fw/g' $filename
sed -i 's/GTGATCTCATATTTAAGTGATTC/primer_fw/g' $filename
sed -i 's/TTCCAAATTCCAGACTTCTGTTCA/primer_fw/g' $filename
sed -i 's/ACAATCTATGCCTGTGAACCCA/primer_fw/g' $filename
sed -i 's/GGAAATGTAGAGATGAGCAATAA/primer_fw/g' $filename
sed -i 's/AGGTGCGGTAGTACAAAGTGA/primer_fw/g' $filename
sed -i 's/ATGGGCTAAGGTATGTTTTACG/primer_fw/g' $filename
sed -i 's/TTGCCAACATCTATACCAAGTCT/primer_fw/g' $filename
sed -i 's/AACACCATAGTGCAATGTGC/primer_fw/g' $filename
sed -i 's/TCCTCTTGTTGATGCCACTT/primer_fw/g' $filename
sed -i 's/CTCCATAAGGGGCATCACAT/primer_fw/g' $filename
sed -i 's/TGGGCTCAAGTTTGGACATTA/primer_fw/g' $filename
sed -i 's/CGATTGGTATAGTGGTCATTGT/primer_fw/g' $filename
sed -i 's/CCATCATACCTTCTTGAAGAG/primer_fw/g' $filename
sed -i 's/CGAAAGCGAAGAGAGTATCG/primer_fw/g' $filename
sed -i 's/GTTCCCAAGGAGAAACCCTA/primer_fw/g' $filename
sed -i 's/AGTTGTACTGTGTGTTGGTC/primer_fw/g' $filename
sed -i 's/CTGCCTCAACCACTTCTTC/primer_fw/g' $filename
sed -i 's/GATTACATCGTGGGTAGGAC/primer_fw/g' $filename
sed -i 's/AAGTGATTTGGTGTGGTGAC/primer_fw/g' $filename
sed -i 's/TGGTCGGATTGAGTGAAG/primer_fw/g' $filename
sed -i 's/ACCCATCCCATGATAGGAG/primer_fw/g' $filename
sed -i 's/CGTGGTTCCCATCCTCTAAA/primer_fw/g' $filename
sed -i 's/TGGCAGCTAAAGGATTAAAGAA/primer_fw/g' $filename
sed -i 's/CCCTAACCCTAGAATCCAATAA/primer_fw/g' $filename
sed -i 's/GAGGAAGGCGACAAGTCATT/primer_fw/g' $filename
sed -i 's/ATGCCCAAAAACGAAAAAGT/primer_fw/g' $filename
sed -i 's/TTTGCACTGCCAGATTCAGA/primer_fw/g' $filename
sed -i 's/TGTTGCTGGGTTGTTGTTAGA/primer_fw/g' $filename
sed -i 's/GGGTAATAGTTCCAGTCTTTG/primer_fw/g' $filename
sed -i 's/TGAGGTTAGGAGCATCTCGT/primer_fw/g' $filename
sed -i 's/GTCCTTCATCGCCTCTTCTT/primer_fw/g' $filename
sed -i 's/GCAACCGACAATGATTACATAG/primer_fw/g' $filename
sed -i 's/CCTAAAACTGAACTTTGCTCAAT/primer_fw/g' $filename
sed -i 's/TCA[AT]ATAAAAGC[TC]ATGAAA[AC]A[GA]GTAGCTGG/primer_fw/g' $filename
sed -i 's/GTCTAATGGATAGGACAGAGG/primer_fw/g' $filename
sed -i 's/GGGAGAGATGGCTGAGTGGAC/primer_fw/g' $filename
sed -i 's/GATCCCGGACGTAATCCTG/primer_fw/g' $filename
sed -i 's/GCCTTTGTTTGGCAAGCTGCTGTAAG/primer_fw/g' $filename
sed -i 's/GGGACGGAAGGATTCGAACC/primer_fw/g' $filename
sed -i 's/CAAGTCGCACGTTGCTTTCTACCACATCGTTT/primer_fw/g' $filename
sed -i 's/CCTGGCCCAACCCTAGACA/primer_fw/g' $filename
sed -i 's/TACGAGATCACCCCTTTCATTC/primer_fw/g' $filename
sed -i 's/GGGCTATTAGCTCAGTGGTAGAGCGC/primer_fw/g' $filename
sed -i 's/TTGCTATGCTTAGTGTGTGACTC/primer_fw/g' $filename
sed -i 's/CCCTTCATTCTTCCTCTATGTTG/primer_fw/g' $filename
sed -i 's/GTAGTTGGATCTCCAAGTTTTTGG/primer_fw/g' $filename
sed -i 's/GGATT[GA]CGTATGGG[AC]AATATTGAAAC/primer_fw/g' $filename
sed -i 's/GGGGATAGAGGGACTTGAAC/primer_fw/g' $filename
sed -i 's/CGAAATCGGTAGACGCTACG/primer_fw/g' $filename
sed -i 's/TGGGTTGCTAACTCAATGG/primer_fw/g' $filename
sed -i 's/CTATTTAAACCATGATCATGAG/primer_fw/g' $filename
sed -i 's/GCGAGTTTTCAAGAAACTGCTCG/primer_fw/g' $filename
sed -i 's/TGTTCCAATATCTTCTTGTCATTT/primer_fw/g' $filename
sed -i 's/GAGGATTAATG[GT]C[GA]GATCC[AT]CAAGG/primer_fw/g' $filename
sed -i 's/GATAGACATCGGTACTCCAGTGC/primer_fw/g' $filename
sed -i 's/TCTACCGATTTCGCCATATC/primer_fw/g' $filename
sed -i 's/CATTACAAATGCGATGCTCT/primer_fw/g' $filename
sed -i 's/CC[TC]GGAGA[GAT]GA[GC][GA][GA][GC][GAT]C[GA][GAT][ACT]TTGG/primer_fw/g' $filename
sed -i 's/GTAATCT[TC]TC[AT]CGATAAAGTCG[GA]TTG/primer_fw/g' $filename
sed -i 's/ACATCACTGCACTTCCACTTGACACC/primer_fw/g' $filename
sed -i 's/ACTTCTGGTTCCGGCGAACGAA/primer_fw/g' $filename
sed -i 's/GTAGTTGGATCTCCAAGTTTTTGG/primer_fw/g' $filename
sed -i 's/GGAAGGTGCGGCTGGATC/primer_fw/g' $filename
sed -i 's/TACGTTC[GA]TGCATAACTTCC/primer_fw/g' $filename