filename=short_seq.fastq

sed -i 's/CCACTTATCTTTCAGGAGTAT/primer_rev/g' $filename
sed -i 's/TAAAAGCCGAGTACTCTACCGTTG/primer_rev/g' $filename
sed -i 's/GAGCATCTTGTATTTCAT[GA]AAAA/primer_rev/g' $filename
sed -i 's/CTCGTGTCACCAGTTCAAAT/primer_rev/g' $filename
sed -i 's/GAGAATCAATCCTACTACTTC/primer_rev/g' $filename
sed -i 's/CTTAATTCATGAGTTGTAGGG/primer_rev/g' $filename
sed -i 's/CTATTCGAAATTCAGAAGAACTGCG/primer_rev/g' $filename
sed -i 's/CAACTCGCACACACTCCCTTT/primer_rev/g' $filename
sed -i 's/AGAGTCCTCC[GCA]AATATTTTGG/primer_rev/g' $filename
sed -i 's/CCAGCAGCAATAACGGAAGCGGC/primer_rev/g' $filename
sed -i 's/AACGAATCACACTTTTACCACTAAAC/primer_rev/g' $filename
sed -i 's/GCCTTCCAAGCTAACGATGCGG/primer_rev/g' $filename
sed -i 's/CATAACCTTGAGGTCACGGGTTC/primer_rev/g' $filename
sed -i 's/TCCTGCCAATATCCACGCCA/primer_rev/g' $filename
sed -i 's/GGGATAGAGGGACTTGAACC/primer_rev/g' $filename
sed -i 's/CTTGACAGTGGTATATGTTG/primer_rev/g' $filename
sed -i 's/GGAAAGGGAGTGTGTGCGAG/primer_rev/g' $filename
sed -i 's/ATAAAGGAGCCGAATGAAAC/primer_rev/g' $filename
sed -i 's/CGGACACATACTTCGTGAAATG/primer_rev/g' $filename
sed -i 's/CCTTCTGAAGAGCACCGCCTTG/primer_rev/g' $filename
sed -i 's/GCCACACACTGCCTCACTCAGC/primer_rev/g' $filename
sed -i 's/GGATAATGCTGCTCACATTTGGAC/primer_rev/g' $filename
sed -i 's/CGAGGCCTGCTTCAGACTGAT/primer_rev/g' $filename
sed -i 's/GCTCTGGACACTTCGGG/primer_rev/g' $filename
sed -i 's/GTAGACTATTTGAGTGGG/primer_rev/g' $filename
sed -i 's/CCCTTTTAACTCAGTGGTAG/primer_rev/g' $filename
sed -i 's/GGGATTGTAGTTCAATTGGT/primer_rev/g' $filename
sed -i 's/CCAGG[GA]ACCAT[AT]GG[GA]TA[GA]T[GT][GAT]GAC/primer_rev/g' $filename
sed -i 's/CACATGGG[GT]GT[GC]AAGAT[AT]GC/primer_rev/g' $filename
sed -i 's/CTATTTACTACG[ACT]CGACGAA/primer_rev/g' $filename
sed -i 's/CCCGCGC[GA]TGGTGGATTCAC/primer_rev/g' $filename
sed -i 's/AGA[GT]ACTTCGTAAGAGACCATT/primer_rev/g' $filename
sed -i 's/ATATCTGTCTCACTAAGCGG/primer_rev/g' $filename
sed -i 's/TGAGCTGCAGATCGTAATGC/primer_rev/g' $filename
sed -i 's/GGGTGATAAATGAACGCTC/primer_rev/g' $filename
sed -i 's/CGCAAAGGCAGATATGG/primer_rev/g' $filename
sed -i 's/CCGTTGAGTTAGCAACCCA/primer_rev/g' $filename
sed -i 's/CTACTCCATCCGACTAGTT/primer_rev/g' $filename
sed -i 's/GGATCGACCGGAAACTCTTC/primer_rev/g' $filename
sed -i 's/CCGGAAACTCTTCCATTC/primer_rev/g' $filename
sed -i 's/GGTAGCGGGAATCGAACCCG/primer_rev/g' $filename
sed -i 's/TTCAAATCCTATTGGACGCAAT/primer_rev/g' $filename
sed -i 's/GTCCAATAGGATTTGAACCTATACC/primer_rev/g' $filename
sed -i 's/CCTGAATAGCTTCTTTCAAAAGGG/primer_rev/g' $filename
sed -i 's/TACCACTGAGTTAAAAGGGC/primer_rev/g' $filename
sed -i 's/ATGACTATAGCCCTTGGTA/primer_rev/g' $filename
sed -i 's/CCACTTGGTTTCAGACTGGG/primer_rev/g' $filename
sed -i 's/AAACGATGTGGTA[GA]AAAGCAAC/primer_rev/g' $filename
sed -i 's/CCCAGTCTGAAACCAAGTGG/primer_rev/g' $filename
sed -i 's/GTGGACGATGAAGGAGAT/primer_rev/g' $filename
sed -i 's/GTAGATTAGGTATTAGTTGGGG/primer_rev/g' $filename
sed -i 's/CCTAGGCTCTATCAAGCGCCGA/primer_rev/g' $filename
sed -i 's/GAATCACTTAAATATGAGATCAC/primer_rev/g' $filename
sed -i 's/TGAACAGAAGTCTGGAATTTGGAA/primer_rev/g' $filename
sed -i 's/TGGGTTCACAGGCATAGATTGT/primer_rev/g' $filename
sed -i 's/TTATTGCTCATCTCTACATTTCC/primer_rev/g' $filename
sed -i 's/TCACTTTGTACTACCGCACCT/primer_rev/g' $filename
sed -i 's/CGTAAAACATACCTTAGCCCAT/primer_rev/g' $filename
sed -i 's/AGACTTGGTATAGATGTTGGCAA/primer_rev/g' $filename
sed -i 's/GCACATTGCACTATGGTGTT/primer_rev/g' $filename
sed -i 's/AAGTGGCATCAACAAGAGGA/primer_rev/g' $filename
sed -i 's/ATGTGATGCCCCTTATGGAG/primer_rev/g' $filename
sed -i 's/TAATGTCCAAACTTGAGCCCA/primer_rev/g' $filename
sed -i 's/ACAATGACCACTATACCAATCG/primer_rev/g' $filename
sed -i 's/CTCTTCAAGAAGGTATGATGG/primer_rev/g' $filename
sed -i 's/CGATACTCTCTTCGCTTTCG/primer_rev/g' $filename
sed -i 's/TAGGGTTTCTCCTTGGGAAC/primer_rev/g' $filename
sed -i 's/GACCAACACACAGTACAACT/primer_rev/g' $filename
sed -i 's/GAAGAAGTGGTTGAGGCAG/primer_rev/g' $filename
sed -i 's/GTCCTACCCACGATGTAATC/primer_rev/g' $filename
sed -i 's/GTCACCACACCAAATCACTT/primer_rev/g' $filename
sed -i 's/CTTCACTCAATCCGACCA/primer_rev/g' $filename
sed -i 's/CTCCTATCATGGGATGGGT/primer_rev/g' $filename
sed -i 's/TTTAGAGGATGGGAACCACG/primer_rev/g' $filename
sed -i 's/TTCTTTAATCCTTTAGCTGCCA/primer_rev/g' $filename
sed -i 's/TTATTGGATTCTAGGGTTAGGG/primer_rev/g' $filename
sed -i 's/AATGACTTGTCGCCTTCCTC/primer_rev/g' $filename
sed -i 's/ACTTTTTCGTTTTTGGGCAT/primer_rev/g' $filename
sed -i 's/TCTGAATCTGGCAGTGCAAA/primer_rev/g' $filename
sed -i 's/TCTAACAACAACCCAGCAACA/primer_rev/g' $filename
sed -i 's/CAAAGACTGGAACTATTACCC/primer_rev/g' $filename
sed -i 's/ACGAGATGCTCCTAACCTCA/primer_rev/g' $filename
sed -i 's/AAGAAGAGGCGATGAAGGAC/primer_rev/g' $filename
sed -i 's/CTATGTAATCATTGTCGGTTGC/primer_rev/g' $filename
sed -i 's/ATTGAGCAAAGTTCAGTTTTAGG/primer_rev/g' $filename
sed -i 's/CCAGCTAC[TC]T[GT]TTTCAT[GA]GCTTTTAT[AT]TGA/primer_rev/g' $filename
sed -i 's/CCTCTGTCCTATCCATTAGAC/primer_rev/g' $filename
sed -i 's/GTCCACTCAGCCATCTCTCCC/primer_rev/g' $filename
sed -i 's/CAGGATTACGTCCGGGATC/primer_rev/g' $filename
sed -i 's/GGTTCGAATCCTTCCGTCCC/primer_rev/g' $filename
sed -i 's/AAACGATGTGGTAGAAAGCAACGTGCGACTTG/primer_rev/g' $filename
sed -i 's/TGTCTAGGGTTGGGCCAGG/primer_rev/g' $filename
sed -i 's/GAATGAAAGGGGTGATCTCGTA/primer_rev/g' $filename
sed -i 's/GCGCTCTACCACTGAGCTAATAGCCC/primer_rev/g' $filename
sed -i 's/GAGTCACACACTAAGCATAGCAA/primer_rev/g' $filename
sed -i 's/CAACATAGAGGAAGAATGAAGGG/primer_rev/g' $filename
sed -i 's/CCAAAAACTTGGAGATCCAACTAC/primer_rev/g' $filename
sed -i 's/GTTTCAATATT[GT]CCCATACG[TC]AATCC/primer_rev/g' $filename
sed -i 's/GTTCAAGTCCCTCTATCCCC/primer_rev/g' $filename
sed -i 's/CGTAGCGTCTACCGATTTCG/primer_rev/g' $filename
sed -i 's/CCATTGAGTTAGCAACCCA/primer_rev/g' $filename
sed -i 's/CTCATGATCATGGTTTAAATAG/primer_rev/g' $filename
sed -i 's/CGAGCAGTTTCTTGAAAACTCGC/primer_rev/g' $filename
sed -i 's/AAATGACAAGAAGATATTGGAACA/primer_rev/g' $filename
sed -i 's/CCTTG[AT]GGATC[TC]G[AC]CATTAATCCTC/primer_rev/g' $filename
sed -i 's/GCACTGGAGTACCGATGTCTATC/primer_rev/g' $filename
sed -i 's/CCACTTATCTTTCAGGAGTAT/primer_rev/g' $filename
sed -i 's/GATATGGCGAAATCGGTAGA/primer_rev/g' $filename
sed -i 's/AGAGCATCGCATTTGTAATG/primer_rev/g' $filename
sed -i 's/CCAA[GAT][ACT][TC]G[ACT][GC][TC][TC][GC]TC[ACT]TCTCC[GA]GG/primer_rev/g' $filename
sed -i 's/CAA[TC]CGACTTTATCG[AT]GA[GA]AGATTAC/primer_rev/g' $filename
sed -i 's/GGTGTCAAGTGGAAGTGCAGTGATGT/primer_rev/g' $filename
sed -i 's/TTCGTTCGCCGGAACCAGAAGT/primer_rev/g' $filename
sed -i 's/GATCCAGCCGCACCTTCC/primer_rev/g' $filename
sed -i 's/GGAAGTTATGCA[TC]GAACGTA/primer_rev/g' $filename
sed -i 's/CTTACAGCAGCTTGCCAAACAAAGGC/primer_rev/g' $filename